import { DEFAULT_FLASH_MS, DEFAULT_INTERVAL_MS } from "./safety";
import type { AudioConfig, MethodId, RecipeId, VisualConfig } from "./types";
import { brainwaveHz, type CategoryModel } from "./themes";
import { withBinaural } from "./recipe-apply";

export type Recipe = {
  id: RecipeId;
  name: string;
  youtubeHook: string;
  methods: MethodId[];
  notes: string;
  visual: VisualConfig;
  audio: Omit<AudioConfig, "binaural"> & {
    binauralPreset?: "delta" | "theta" | "alpha" | "beta" | "off";
  };
};

export const RECIPES: Recipe[] = [
  {
    id: "classic_rain_whisper",
    name: "Classic rain whisper",
    youtubeHook: "The most common YouTube mix: rain bed, barely-there voice.",
    methods: ["whisper_mask", "void_mirror", "text_rsvp"],
    notes: "Keep the voice just under the rain. Headphones optional.",
    visual: {
      mode: "text_rsvp",
      flashDurationMs: DEFAULT_FLASH_MS,
      intervalMs: DEFAULT_INTERVAL_MS,
      opacity: 0.85,
      mask: "forward",
      textColor: "#f3ead7",
      bgColor: "#000000",
      carrier: "black",
    },
    audio: {
      bed: "rain",
      affirmationGainDb: -22,
      reverse: false,
      alsoForward: true,
      speed: 1,
      layers: 2,
      whisper: true,
      binauralPreset: "alpha",
      isochronic: { enabled: false, hz: 10 },
      silentCarrier: { enabled: false, hz: 18500, depth: 0.35 },
      eightD: false,
    },
  },
  {
    id: "silent_omega",
    name: "Silent omega",
    youtubeHook: "Ultrasonic carrier with a black screen — the 'silent' format.",
    methods: ["silent_omega", "void_mirror", "text_rsvp"],
    notes: "Use headphones. Tiny speakers often cannot reproduce 18.5 kHz.",
    visual: {
      mode: "void",
      flashDurationMs: 16,
      intervalMs: 5000,
      opacity: 0.7,
      mask: "none",
      textColor: "#ffffff",
      bgColor: "#000000",
      carrier: "black",
    },
    audio: {
      bed: "brown",
      affirmationGainDb: -28,
      reverse: false,
      alsoForward: false,
      speed: 1,
      layers: 1,
      whisper: false,
      binauralPreset: "theta",
      isochronic: { enabled: false, hz: 6 },
      silentCarrier: { enabled: true, hz: 18500, depth: 0.5 },
      eightD: false,
    },
  },
  {
    id: "results_flash",
    name: "Results-picture flash",
    youtubeHook: "Desired-reality stills flashed 1–2 frames every few seconds.",
    methods: ["flash_images", "whisper_mask", "dual_channel"],
    notes: "Link a Drive folder of results pictures or generate stills from the theme.",
    visual: {
      mode: "flash_images",
      flashDurationMs: 42,
      intervalMs: 3000,
      opacity: 1,
      mask: "forward",
      textColor: "#ffffff",
      bgColor: "#000000",
      carrier: "black",
    },
    audio: {
      bed: "rain",
      affirmationGainDb: -20,
      reverse: false,
      alsoForward: true,
      speed: 1,
      layers: 3,
      whisper: true,
      binauralPreset: "alpha",
      isochronic: { enabled: false, hz: 10 },
      silentCarrier: { enabled: false, hz: 18500, depth: 0.3 },
      eightD: false,
    },
  },
  {
    id: "twenty_fifth_frame",
    name: "25th-frame insert",
    youtubeHook: "One-frame cutaway, the classic subliminal-cut technique.",
    methods: ["frame_insert", "whisper_mask"],
    notes: "At 24–30 fps a single frame sits near the edge of conscious naming.",
    visual: {
      mode: "frame_insert",
      flashDurationMs: 16,
      intervalMs: 4500,
      opacity: 1,
      mask: "noise",
      textColor: "#efe7d6",
      bgColor: "#050505",
      carrier: "gradient",
    },
    audio: {
      bed: "pad",
      affirmationGainDb: -24,
      reverse: false,
      alsoForward: true,
      speed: 1,
      layers: 2,
      whisper: true,
      binauralPreset: "alpha",
      isochronic: { enabled: false, hz: 10 },
      silentCarrier: { enabled: false, hz: 18500, depth: 0.3 },
      eightD: false,
    },
  },
  {
    id: "theta_sleep",
    name: "Theta sleep",
    youtubeHook: "Brown noise, theta binaural, sparse morphs — overnight loops.",
    methods: ["binaural", "morph_overlay", "whisper_mask"],
    notes: "Headphones for the beat. Keep flashes rare so they do not wake you.",
    visual: {
      mode: "morph_overlay",
      flashDurationMs: 180,
      intervalMs: 8000,
      opacity: 0.08,
      mask: "none",
      textColor: "#dce3f2",
      bgColor: "#08090e",
      carrier: "black",
    },
    audio: {
      bed: "brown",
      affirmationGainDb: -26,
      reverse: false,
      alsoForward: true,
      speed: 0.92,
      layers: 2,
      whisper: true,
      binauralPreset: "theta",
      isochronic: { enabled: false, hz: 6 },
      silentCarrier: { enabled: false, hz: 18500, depth: 0.25 },
      eightD: false,
    },
  },
  {
    id: "affirmation_storm",
    name: "Affirmation storm",
    youtubeHook: "Many overlapping voices, the '600 affirmations' stack.",
    methods: ["layered_storm", "speed_stack", "text_rsvp"],
    notes: "Chaos is the point. Conscious parsing should fail; the script is still there.",
    visual: {
      mode: "text_rsvp",
      flashDurationMs: 50,
      intervalMs: 2200,
      opacity: 0.55,
      mask: "none",
      textColor: "#efe7d6",
      bgColor: "#000000",
      carrier: "black",
    },
    audio: {
      bed: "pink",
      affirmationGainDb: -18,
      reverse: false,
      alsoForward: true,
      speed: 1.35,
      layers: 8,
      whisper: true,
      binauralPreset: "alpha",
      isochronic: { enabled: false, hz: 10 },
      silentCarrier: { enabled: false, hz: 18500, depth: 0.2 },
      eightD: false,
    },
  },
  {
    id: "dual_hemisphere",
    name: "Dual hemisphere",
    youtubeHook: "Forward in one ear, reverse in the other, plus image flashes.",
    methods: ["backmask", "binaural", "flash_images", "dual_channel"],
    notes: "Headphones required. Reverse sits on the opposite pan from forward.",
    visual: {
      mode: "dual",
      flashDurationMs: 33,
      intervalMs: 3500,
      opacity: 0.9,
      mask: "forward",
      textColor: "#ffffff",
      bgColor: "#000000",
      carrier: "black",
    },
    audio: {
      bed: "rain",
      affirmationGainDb: -21,
      reverse: true,
      alsoForward: true,
      speed: 1,
      layers: 2,
      whisper: true,
      binauralPreset: "theta",
      isochronic: { enabled: false, hz: 6 },
      silentCarrier: { enabled: false, hz: 18500, depth: 0.3 },
      eightD: false,
    },
  },
  {
    id: "boosted_mirror",
    name: "Boosted mirror",
    youtubeHook: "Supraliminal: longer flashes and a louder whisper you can almost catch.",
    methods: ["void_mirror", "text_rsvp", "whisper_mask"],
    notes: "Use when you want to read the script once, then drop the volume later.",
    visual: {
      mode: "text_rsvp",
      flashDurationMs: 220,
      intervalMs: 2500,
      opacity: 1,
      mask: "none",
      textColor: "#ffffff",
      bgColor: "#000000",
      carrier: "black",
    },
    audio: {
      bed: "ocean",
      affirmationGainDb: -12,
      reverse: false,
      alsoForward: true,
      speed: 1,
      layers: 1,
      whisper: true,
      binauralPreset: "alpha",
      isochronic: { enabled: false, hz: 10 },
      silentCarrier: { enabled: false, hz: 18500, depth: 0.2 },
      eightD: false,
    },
  },
  {
    id: "night_loop",
    name: "Night loop",
    youtubeHook: "Brown noise plus isochronic pulses for all-night play.",
    methods: ["isochronic", "whisper_mask", "void_mirror"],
    notes: "Speaker-friendly. Flashes stay rare.",
    visual: {
      mode: "void",
      flashDurationMs: 33,
      intervalMs: 9000,
      opacity: 0.4,
      mask: "none",
      textColor: "#cfd6e4",
      bgColor: "#05060a",
      carrier: "black",
    },
    audio: {
      bed: "brown",
      affirmationGainDb: -27,
      reverse: false,
      alsoForward: true,
      speed: 0.9,
      layers: 2,
      whisper: true,
      binauralPreset: "delta",
      isochronic: { enabled: true, hz: 4 },
      silentCarrier: { enabled: false, hz: 18500, depth: 0.2 },
      eightD: false,
    },
  },
  {
    id: "aesthetic_lofi",
    name: "Aesthetic lo-fi",
    youtubeHook: "Gradient stills, soft pad, circling whisper — the pretty thumbnail mix.",
    methods: ["eight_d", "morph_overlay", "whisper_mask"],
    notes: "Export this one if you want a YouTube-looking visual with gentle audio.",
    visual: {
      mode: "morph_overlay",
      flashDurationMs: 120,
      intervalMs: 5000,
      opacity: 0.14,
      mask: "none",
      textColor: "#f4e7c3",
      bgColor: "#0c0d0b",
      carrier: "gradient",
    },
    audio: {
      bed: "pad",
      affirmationGainDb: -20,
      reverse: false,
      alsoForward: true,
      speed: 1,
      layers: 3,
      whisper: true,
      binauralPreset: "alpha",
      isochronic: { enabled: false, hz: 10 },
      silentCarrier: { enabled: false, hz: 18500, depth: 0.25 },
      eightD: true,
    },
  },
  {
    id: "speed_compressed",
    name: "Speed compressed",
    youtubeHook: "Fast stacked speech used in 'listen once a day' study tracks.",
    methods: ["speed_stack", "layered_storm", "text_rsvp"],
    notes: "Raise speed toward 2–4x for more repetitions per minute.",
    visual: {
      mode: "text_rsvp",
      flashDurationMs: 40,
      intervalMs: 2800,
      opacity: 0.7,
      mask: "forward",
      textColor: "#e7eef6",
      bgColor: "#0b0d10",
      carrier: "black",
    },
    audio: {
      bed: "brown",
      affirmationGainDb: -19,
      reverse: false,
      alsoForward: true,
      speed: 2.2,
      layers: 4,
      whisper: false,
      binauralPreset: "beta",
      isochronic: { enabled: true, hz: 14 },
      silentCarrier: { enabled: false, hz: 18500, depth: 0.2 },
      eightD: false,
    },
  },
  {
    id: "morph_void",
    name: "Morph void",
    youtubeHook: "Nearly invisible overlays on black, with a reversed under-layer.",
    methods: ["morph_overlay", "backmask", "silent_omega"],
    notes: "Three depths at once: morph, reverse, silent carrier.",
    visual: {
      mode: "morph_overlay",
      flashDurationMs: 90,
      intervalMs: 6000,
      opacity: 0.07,
      mask: "none",
      textColor: "#f6e4ea",
      bgColor: "#000000",
      carrier: "black",
    },
    audio: {
      bed: "ocean",
      affirmationGainDb: -25,
      reverse: true,
      alsoForward: true,
      speed: 1,
      layers: 2,
      whisper: true,
      binauralPreset: "theta",
      isochronic: { enabled: false, hz: 6 },
      silentCarrier: { enabled: true, hz: 18500, depth: 0.4 },
      eightD: false,
    },
  },
];

export function recipeById(id: RecipeId): Recipe {
  const found = RECIPES.find((r) => r.id === id);
  if (!found) throw new Error(`Unknown recipe ${id}`);
  return found;
}

export function isRecipeId(value: string): value is RecipeId {
  return RECIPES.some((r) => r.id === value);
}

export function applyCategoryToRecipe(recipe: Recipe, category: CategoryModel): {
  visual: VisualConfig;
  audio: AudioConfig;
} {
  const beat = brainwaveHz(recipe.audio.binauralPreset ?? category.brainwave);
  const audio: AudioConfig = withBinaural(
    recipe.audio,
    beat,
    recipe.audio.bed === "rain" ? category.bed : recipe.audio.bed,
  );
  const visual: VisualConfig = {
    ...recipe.visual,
    textColor: category.palette.fg,
    bgColor: recipe.visual.carrier === "black" ? "#000000" : category.palette.bg,
  };
  return { visual, audio };
}
