import type { DamageType } from "../types";

export interface EnemyDef {
  id: string;
  name: string;
  title: string;
  lore: string;
  hp: number;
  power: number;
  armor: number;
  xp: number;
  gold: number;
  canFlee: boolean;
  boss?: boolean;
  resists?: Partial<Record<DamageType, number>>;
  intents: string[];
  loot?: { defId: string; chance: number }[];
  winFlag?: string;
  winMemory?: string;
}

export const ENEMIES: Record<string, EnemyDef> = {
  ash_rat: {
    id: "ash_rat",
    name: "Ash Rat",
    title: "A mistake with teeth",
    lore: "It nested in a cold hearth and learned hunger from the idea of fire.",
    hp: 16,
    power: 4,
    armor: 0,
    xp: 12,
    gold: 4,
    canFlee: true,
    intents: ["nips at your ankle", "shrieks in a key that hurts", "goes for the fingers"],
  },
  cutpurse: {
    id: "cutpurse",
    name: "Cutpurse",
    title: "Hunger with a knife",
    lore: "Emberhearth's alleys mint two things: rumors and this.",
    hp: 22,
    power: 6,
    armor: 1,
    xp: 16,
    gold: 8,
    canFlee: true,
    intents: ["feints low", "goes for your purse-string", "spits and lunges"],
  },
  veilwolf: {
    id: "veilwolf",
    name: "Veilwolf",
    title: "A hole in the shape of a hunter",
    lore: "It has too many joints. The eyes are polite. The rest is not.",
    hp: 28,
    power: 8,
    armor: 1,
    xp: 22,
    gold: 6,
    canFlee: true,
    resists: { aether: -0.2 },
    intents: ["circles, tasting the air", "unhinges a jaw it did not have", "goes still — worse"],
  },
  hollow_stag: {
    id: "hollow_stag",
    name: "Hollow Stag",
    title: "Crown of the Green Wound",
    lore: "Where a heart should be, a lantern of wrong light. The Veilwood bows when it passes.",
    hp: 88,
    power: 11,
    armor: 3,
    xp: 70,
    gold: 24,
    canFlee: false,
    boss: true,
    resists: { physical: 0.15, aether: -0.15 },
    intents: [
      "lowers the crown of antlers",
      "the lantern-heart flares",
      "hooves write a warning in dirt",
    ],
    loot: [{ defId: "emberheart", chance: 1 }],
    winFlag: "anchor.ember",
    winMemory: "You took the Ember Anchor from a king that was already a grave.",
  },
  drowned_singer: {
    id: "drowned_singer",
    name: "Drowned Singer",
    title: "A mouth full of tide",
    lore: "It still knows three hymns. All of them are about going under.",
    hp: 32,
    power: 9,
    armor: 1,
    xp: 24,
    gold: 10,
    canFlee: true,
    resists: { fire: 0.2, aether: -0.1 },
    intents: ["inhales the dock-fog", "sings a note that rusts thought", "reaches with wet sleeves"],
  },
  drowned_choir: {
    id: "drowned_choir",
    name: "Drowned Choir",
    title: "The fog bell's congregation",
    lore: "Many throats, one appetite. Saltmoor paid it in sailors for a generation.",
    hp: 96,
    power: 12,
    armor: 2,
    xp: 80,
    gold: 30,
    canFlee: false,
    boss: true,
    resists: { fire: 0.25, holy: -0.2 },
    intents: [
      "harmonizes wrong",
      "the bell rings without a ringer",
      "hands of water find your throat",
    ],
    loot: [{ defId: "tide_anchor", chance: 1 }],
    winFlag: "anchor.tide",
    winMemory: "You silenced a choir that had been drowning the same note for a hundred years.",
  },
  archive_shade: {
    id: "archive_shade",
    name: "Archive Shade",
    title: "A footnote that got up",
    lore: "Knowledge that outlived its reader. It wants to be cited. It will settle for being feared.",
    hp: 36,
    power: 10,
    armor: 2,
    xp: 28,
    gold: 12,
    canFlee: true,
    resists: { physical: 0.25, aether: -0.25 },
    intents: ["indexes you", "quotes a law you broke", "turns a page in the air"],
  },
  cinder_acolyte: {
    id: "cinder_acolyte",
    name: "Cinder Acolyte",
    title: "Faith, overcooked",
    lore: "They prayed until the prayer caught. Now they are the smoke.",
    hp: 34,
    power: 10,
    armor: 2,
    xp: 26,
    gold: 12,
    canFlee: true,
    resists: { fire: 0.4, holy: 0.1 },
    intents: ["raises a brand", "chants a wick-prayer", "opens a mouth of sparks"],
  },
  saint_of_cinders: {
    id: "saint_of_cinders",
    name: "Saint of Cinders",
    title: "The cathedral's last honest fire",
    lore: "Canonized by accident. She keeps the Ash Anchor in a ribcage that will not cool.",
    hp: 104,
    power: 13,
    armor: 3,
    xp: 90,
    gold: 36,
    canFlee: false,
    boss: true,
    resists: { fire: 0.5, holy: -0.15 },
    intents: [
      "spreads arms like stained glass",
      "the nave inhales",
      "a sermon of sparks",
    ],
    loot: [{ defId: "ash_anchor", chance: 1 }],
    winFlag: "anchor.ash",
    winMemory: "You took a saint's last heat and did not ask permission of heaven.",
  },
  rift_wisp: {
    id: "rift_wisp",
    name: "Rift Wisp",
    title: "A thought the sky dropped",
    lore: "It is not hostile so much as incomplete. Completing it would be worse.",
    hp: 24,
    power: 11,
    armor: 0,
    xp: 20,
    gold: 0,
    canFlee: true,
    resists: { aether: 0.3, physical: -0.2 },
    intents: ["flickers through your memories", "asks your name incorrectly", "brightens"],
  },
  hollow_king: {
    id: "hollow_king",
    name: "The Hollow King",
    title: "What the Veil wears when it wants a face",
    lore: "Not a monarch. A habit. The Unmade learned kingship from watching us kneel.",
    hp: 150,
    power: 16,
    armor: 4,
    xp: 0,
    gold: 0,
    canFlee: false,
    boss: true,
    resists: { physical: 0.1, aether: 0.1, fire: 0.1, holy: -0.1 },
    intents: [
      "crowns itself in your doubts",
      "the Rift leans in",
      "speaks in Mira's voice, then not",
      "opens a court of absences",
    ],
    winFlag: "king.fallen",
    winMemory: "You put a king-shaped hole back into the dark it came from.",
  },
};
