import type { ClassId, DamageType } from "../types";

export interface SkillDef {
  id: string;
  name: string;
  mp: number;
  desc: string;
  type: "strike" | "guard" | "heal" | "hex" | "fire" | "holy" | "execute" | "shift";
  damageType?: DamageType;
  power: number;
  classes: ClassId[];
}

export const SKILLS: Record<string, SkillDef> = {
  rend: {
    id: "rend",
    name: "Rend",
    mp: 0,
    desc: "A straightforward spear-cut. The forest does not applaud. It nods.",
    type: "strike",
    damageType: "physical",
    power: 7,
    classes: ["warden"],
  },
  barkward: {
    id: "barkward",
    name: "Barkward",
    mp: 6,
    desc: "Skin remembers being tree. The next hurt arrives late and smaller.",
    type: "guard",
    power: 0,
    classes: ["warden"],
  },
  mending_root: {
    id: "mending_root",
    name: "Mending Root",
    mp: 8,
    desc: "Green thread pulls a wound closed as if embarrassed by it.",
    type: "heal",
    power: 16,
    classes: ["warden"],
  },
  earths_claim: {
    id: "earths_claim",
    name: "Earth's Claim",
    mp: 12,
    desc: "The ground takes a dislike to your enemy. It is a serious dislike.",
    type: "strike",
    damageType: "physical",
    power: 16,
    classes: ["warden"],
  },
  aether_needle: {
    id: "aether_needle",
    name: "Aether Needle",
    mp: 4,
    desc: "A thin, unkind stitch through whatever they were using as a soul.",
    type: "strike",
    damageType: "aether",
    power: 8,
    classes: ["hexweaver"],
  },
  hex_mark: {
    id: "hex_mark",
    name: "Hex Mark",
    mp: 7,
    desc: "You write their true name wrong on purpose. The world corrects it with pain.",
    type: "hex",
    damageType: "aether",
    power: 4,
    classes: ["hexweaver"],
  },
  veilstep: {
    id: "veilstep",
    name: "Veilstep",
    mp: 6,
    desc: "You are briefly a rumor. The next blow you land is from an unfair angle.",
    type: "shift",
    power: 0,
    classes: ["hexweaver"],
  },
  unmake: {
    id: "unmake",
    name: "Unmake",
    mp: 14,
    desc: "A sentence with no subject. Things that hear it lose track of existing.",
    type: "strike",
    damageType: "aether",
    power: 18,
    classes: ["hexweaver"],
  },
  cinder_cut: {
    id: "cinder_cut",
    name: "Cinder Cut",
    mp: 0,
    desc: "Steel, then heat, then the idea of heat. It is usually enough.",
    type: "fire",
    damageType: "fire",
    power: 8,
    classes: ["ashblade"],
  },
  ember_dash: {
    id: "ember_dash",
    name: "Ember Dash",
    mp: 5,
    desc: "You arrive already mid-swing. Courtesy is for people with more time.",
    type: "shift",
    damageType: "fire",
    power: 6,
    classes: ["ashblade"],
  },
  blood_price: {
    id: "blood_price",
    name: "Blood Price",
    mp: 0,
    desc: "You pay in red. The weapon considers this a compelling argument.",
    type: "strike",
    damageType: "physical",
    power: 14,
    classes: ["ashblade"],
  },
  execute: {
    id: "execute",
    name: "Execute",
    mp: 8,
    desc: "For things that should already be dead. The world often agrees.",
    type: "execute",
    damageType: "physical",
    power: 10,
    classes: ["ashblade"],
  },
  smite: {
    id: "smite",
    name: "Smite",
    mp: 3,
    desc: "A blow with a thesis. The thesis is: you should not be doing that.",
    type: "holy",
    damageType: "holy",
    power: 8,
    classes: ["oathbound"],
  },
  aegis: {
    id: "aegis",
    name: "Aegis",
    mp: 6,
    desc: "Light stands up in front of you and refuses to sit down.",
    type: "guard",
    power: 0,
    classes: ["oathbound"],
  },
  oathfire: {
    id: "oathfire",
    name: "Oathfire",
    mp: 9,
    desc: "A flame that only burns broken promises. Conveniently, most enemies have some.",
    type: "holy",
    damageType: "holy",
    power: 13,
    classes: ["oathbound"],
  },
  judgment: {
    id: "judgment",
    name: "Judgment",
    mp: 12,
    desc: "You ask the Veil to pick a side. Sometimes it does.",
    type: "execute",
    damageType: "holy",
    power: 12,
    classes: ["oathbound"],
  },
};
